name: Testing and Docker Image Build/Push CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3.1.4
        with:
          python-version: ${{ matrix.python-version }}
      - 
        name: Install Python Dependencies with UV
        run: |
          pipx install uv
          uv pip install -e . --system

  docker:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.10.6
          buildkitd-flags: --debug
      - 
        id: authgcp
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - 
        name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GAR_REGION }}-docker.pkg.dev
          username: _json_key
          password: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.GAR_REPO }}/bilka2go-scraper:latest
